// <auto-generated />
using GameOfThronesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameOfThronesAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250922180620_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("GameOfThronesAPI.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HouseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NovaCasaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StrongholdId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.HasIndex("NovaCasaId");

                    b.HasIndex("StrongholdId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("GameOfThronesAPI.Models.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OverlordHouseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StrongholdId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OverlordHouseId");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("GameOfThronesAPI.Models.Stronghold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HouseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HouseId")
                        .IsUnique();

                    b.ToTable("Strongholds");
                });

            modelBuilder.Entity("GameOfThronesAPI.Models.Character", b =>
                {
                    b.HasOne("GameOfThronesAPI.Models.House", "House")
                        .WithMany("Characters")
                        .HasForeignKey("HouseId");

                    b.HasOne("GameOfThronesAPI.Models.House", "NovaCasa")
                        .WithMany()
                        .HasForeignKey("NovaCasaId");

                    b.HasOne("GameOfThronesAPI.Models.Stronghold", null)
                        .WithMany("Residents")
                        .HasForeignKey("StrongholdId");

                    b.Navigation("House");

                    b.Navigation("NovaCasa");
                });

            modelBuilder.Entity("GameOfThronesAPI.Models.House", b =>
                {
                    b.HasOne("GameOfThronesAPI.Models.House", "OverlordHouse")
                        .WithMany("Vassalos")
                        .HasForeignKey("OverlordHouseId");

                    b.Navigation("OverlordHouse");
                });

            modelBuilder.Entity("GameOfThronesAPI.Models.Stronghold", b =>
                {
                    b.HasOne("GameOfThronesAPI.Models.House", "House")
                        .WithOne("Stronghold")
                        .HasForeignKey("GameOfThronesAPI.Models.Stronghold", "HouseId");

                    b.Navigation("House");
                });

            modelBuilder.Entity("GameOfThronesAPI.Models.House", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Stronghold");

                    b.Navigation("Vassalos");
                });

            modelBuilder.Entity("GameOfThronesAPI.Models.Stronghold", b =>
                {
                    b.Navigation("Residents");
                });
#pragma warning restore 612, 618
        }
    }
}
