// <auto-generated />
using System;
using GameOfThronesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameOfThronesAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CharacterEvent", b =>
                {
                    b.Property<int>("CharactersId")
                        .HasColumnType("integer");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.HasKey("CharactersId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("CharacterEvent");
                });

            modelBuilder.Entity("EventHouse", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("HousesId")
                        .HasColumnType("integer");

                    b.HasKey("EventId", "HousesId");

                    b.HasIndex("HousesId");

                    b.ToTable("EventHouse");
                });

            modelBuilder.Entity("GameOfThronesAPI.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int?>("FortalezaId")
                        .HasColumnType("integer");

                    b.Property<int?>("HouseId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NovaCasaId")
                        .HasColumnType("integer");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FortalezaId");

                    b.HasIndex("HouseId");

                    b.HasIndex("NovaCasaId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("GameOfThronesAPI.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StrongholdId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StrongholdId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("GameOfThronesAPI.Models.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Idade")
                        .HasColumnType("integer");

                    b.Property<string>("Lema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OverlordHouseId")
                        .HasColumnType("integer");

                    b.Property<int?>("StrongholdId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OverlordHouseId");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("GameOfThronesAPI.Models.Stronghold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int?>("HouseId")
                        .HasColumnType("integer");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HouseId")
                        .IsUnique();

                    b.ToTable("Strongholds");
                });

            modelBuilder.Entity("GameOfThronesAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CharacterEvent", b =>
                {
                    b.HasOne("GameOfThronesAPI.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameOfThronesAPI.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventHouse", b =>
                {
                    b.HasOne("GameOfThronesAPI.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameOfThronesAPI.Models.House", null)
                        .WithMany()
                        .HasForeignKey("HousesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameOfThronesAPI.Models.Character", b =>
                {
                    b.HasOne("GameOfThronesAPI.Models.Stronghold", "Fortaleza")
                        .WithMany("Residents")
                        .HasForeignKey("FortalezaId");

                    b.HasOne("GameOfThronesAPI.Models.House", "House")
                        .WithMany("Characters")
                        .HasForeignKey("HouseId");

                    b.HasOne("GameOfThronesAPI.Models.House", "NovaCasa")
                        .WithMany()
                        .HasForeignKey("NovaCasaId");

                    b.Navigation("Fortaleza");

                    b.Navigation("House");

                    b.Navigation("NovaCasa");
                });

            modelBuilder.Entity("GameOfThronesAPI.Models.Event", b =>
                {
                    b.HasOne("GameOfThronesAPI.Models.Stronghold", "Stronghold")
                        .WithMany()
                        .HasForeignKey("StrongholdId");

                    b.Navigation("Stronghold");
                });

            modelBuilder.Entity("GameOfThronesAPI.Models.House", b =>
                {
                    b.HasOne("GameOfThronesAPI.Models.House", "OverlordHouse")
                        .WithMany("Vassalos")
                        .HasForeignKey("OverlordHouseId");

                    b.Navigation("OverlordHouse");
                });

            modelBuilder.Entity("GameOfThronesAPI.Models.Stronghold", b =>
                {
                    b.HasOne("GameOfThronesAPI.Models.House", "House")
                        .WithOne("Stronghold")
                        .HasForeignKey("GameOfThronesAPI.Models.Stronghold", "HouseId");

                    b.Navigation("House");
                });

            modelBuilder.Entity("GameOfThronesAPI.Models.House", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Stronghold");

                    b.Navigation("Vassalos");
                });

            modelBuilder.Entity("GameOfThronesAPI.Models.Stronghold", b =>
                {
                    b.Navigation("Residents");
                });
#pragma warning restore 612, 618
        }
    }
}
